project 'BaiSiBuDeJie_Imitate.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiSiBuDeJie_Imitate' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiSiBuDeJie_Imitate
  use_frameworks!
  
  pod 'AFNetworking','~> 3.0.4'
  pod 'MBProgressHUD'
  pod 'MJExtension','~> 3.0.10'
  pod 'SDWebImage','~> 3.7.5'
end
